apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketserver
spec:
  selector:
    matchLabels:
      app: socketserver
  replicas: 1
  template:
    metadata:
      labels:
        app: socketserver
    spec:
      containers:
        - name: socketserver
          image: phonglai0809/socketserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081          